version: '3'

volumes:
  good-night-dev_db_vol:
    driver: local

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: good-night-dev-db
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: good-night-dev-db
    ports:
      - '3306:3306'
    volumes:
      - good-night-dev_db_vol:/var/lib/mysql